### ISSUE TITLE
Tabel1 结果咨询

### ISSUE THREAD

**Issue by jingmu123** [linzehui/mRASP#14]
感谢公开！关于 Tabel 1 的 一些列实验结果，所有的Fine-tuning数据都是来源于预训练的吗（或者只有En-De,En-Fr,En-Ro是来自于WMT公开数据集，其他都是预训练使用的训练集）？

**Comment by PANXiao1994** [comment]
你好，除了有WMT数据的语向，其余的都是直接用预训练的语料fine-tune的。

**Comment by jingmu123** [comment]
谢谢回复，已明白
