### ISSUE TITLE
En-Fr微调模型checkpoint下载链接失效

### ISSUE THREAD

**Issue by luxinyu1** [linzehui/mRASP#16]
似乎所有的微调模型的下载链接都失效了。
icloud云盘显示“所有者已停止共享，或者您无权打开此项”。

**Comment by linzehui** [comment]
你好，正在将数据迁移到其他地方，过两天会更新链接

**Comment by luxinyu1** [comment]
> 你好，正在将数据迁移到其他地方，过两天会更新链接

知道啦，谢谢您嘞

**Comment by leonodelee** [comment]
您好，请问我直接用您的en-de模型在toy数据形成的二进制文件上跑，出现以下错误是为什么呢？hydra.errors.ConfigCompositionException: Error merging override generation.print_alignment=False

**Comment by linzehui** [comment]
> > 你好，正在将数据迁移到其他地方，过两天会更新链接
> 
> 知道啦，谢谢您嘞

你好，不好意思，最近由于一些原因没法及时更新，如果你还有下载的需求，请发邮件给我，我会随信附上相应的文件的。

**Comment by linzehui** [comment]
已更新下载链接
