### ISSUE TITLE
confused about preprocess pipeline

### ISSUE THREAD

**Issue by SefaZeng** [linzehui/mRASP#2]
The output path in train.yml is /data00/home/panxiao.94/experiments/pmnmt/experiments/toy/data/prep/train.
But the data path in transformer_big.yml is /data00/home/panxiao.94/experiments/pmnmt/experiments/toy/data/pre-train.
So,.. is there some steps lost about the preprocess phase ?

**Comment by PANXiao1994** [comment]
> The output path in train.yml is /data00/home/panxiao.94/experiments/pmnmt/experiments/toy/data/prep/train.
> But the data path in transformer_big.yml is /data00/home/panxiao.94/experiments/pmnmt/experiments/toy/data/pre-train.
> So,.. is there some steps lost about the preprocess phase ?

Hi,

First, you should note that the final output path is ${merged_output_path} in experiments/example/configs/preprocess/train.yml

Second, there is indeed one step between preprocessing and pre-train: binarize the data before training. I will modify the README.md to make the steps easier to follow. You can refer to the file experiments/example/bin.sh or only run the script below to get the binarized data.

```bash
# preprocess pre-train train data
fairseq-preprocess \
        --source-lang src --target-lang trg \
        --srcdict ${PROJECT_ROOT}/experiments/toy/vocab/vocab.bpe.${subword_bpe_merge_ops} \
        --tgtdict ${PROJECT_ROOT}/experiments/toy/vocab/vocab.bpe.${subword_bpe_merge_ops} \
        --trainpref ${PROJECT_ROOT}/experiments/toy/merged_data/train \
        --validpref ${PROJECT_ROOT}/experiments/toy/merged_data/dev \
        --destdir ${PROJECT_ROOT}/experiments/toy/data/pre-train \
        --workers ${num_cpus}
```

**Comment by SefaZeng** [comment]
> > The output path in train.yml is /data00/home/panxiao.94/experiments/pmnmt/experiments/toy/data/prep/train.
> > But the data path in transformer_big.yml is /data00/home/panxiao.94/experiments/pmnmt/experiments/toy/data/pre-train.
> > So,.. is there some steps lost about the preprocess phase ?
> 
> Hi,
> 
> First, you should note that the final output path is ${merged_output_path} in experiments/example/configs/preprocess/train.yml
> 
> Second, there is indeed one step between preprocessing and pre-train: binarize the data before training. I will modify the README.md to make the steps easier to follow. You can refer to the file experiments/example/bin.sh or only run the script below to get the binarized data.
> 
> ```shell
> # preprocess pre-train train data
> fairseq-preprocess \
>         --source-lang src --target-lang trg \
>         --srcdict ${PROJECT_ROOT}/experiments/toy/vocab/vocab.bpe.${subword_bpe_merge_ops} \
>         --tgtdict ${PROJECT_ROOT}/experiments/toy/vocab/vocab.bpe.${subword_bpe_merge_ops} \
>         --trainpref ${PROJECT_ROOT}/experiments/toy/merged_data/train \
>         --validpref ${PROJECT_ROOT}/experiments/toy/merged_data/dev \
>         --destdir ${PROJECT_ROOT}/experiments/toy/data/pre-train \
>         --workers ${num_cpus}
> ```

That's cool! Thanks for your reply. And still another question, how many gpus is needed for the results in the paper. Is 4 enough?

**Comment by PANXiao1994** [comment]
> > > The output path in train.yml is /data00/home/panxiao.94/experiments/pmnmt/experiments/toy/data/prep/train.
> > > But the data path in transformer_big.yml is /data00/home/panxiao.94/experiments/pmnmt/experiments/toy/data/pre-train.
> > > So,.. is there some steps lost about the preprocess phase ?
> > 
> > 
> > Hi,
> > First, you should note that the final output path is ${merged_output_path} in experiments/example/configs/preprocess/train.yml
> > Second, there is indeed one step between preprocessing and pre-train: binarize the data before training. I will modify the README.md to make the steps easier to follow. You can refer to the file experiments/example/bin.sh or only run the script below to get the binarized data.
> > ```shell
> > # preprocess pre-train train data
> > fairseq-preprocess \
> >         --source-lang src --target-lang trg \
> >         --srcdict ${PROJECT_ROOT}/experiments/toy/vocab/vocab.bpe.${subword_bpe_merge_ops} \
> >         --tgtdict ${PROJECT_ROOT}/experiments/toy/vocab/vocab.bpe.${subword_bpe_merge_ops} \
> >         --trainpref ${PROJECT_ROOT}/experiments/toy/merged_data/train \
> >         --validpref ${PROJECT_ROOT}/experiments/toy/merged_data/dev \
> >         --destdir ${PROJECT_ROOT}/experiments/toy/data/pre-train \
> >         --workers ${num_cpus}
> > ```
> 
> That's cool! Thanks for your reply. And still another question, how many gpus is needed for the results in the paper. Is 4 enough?

Yes, you can use 4 gpus, and at the same time you can increase `update_freq` to mimic a larger batch size.

**Comment by SefaZeng** [comment]
> > > > The output path in train.yml is /data00/home/panxiao.94/experiments/pmnmt/experiments/toy/data/prep/train.
> > > > But the data path in transformer_big.yml is /data00/home/panxiao.94/experiments/pmnmt/experiments/toy/data/pre-train.
> > > > So,.. is there some steps lost about the preprocess phase ?
> > > 
> > > 
> > > Hi,
> > > First, you should note that the final output path is ${merged_output_path} in experiments/example/configs/preprocess/train.yml
> > > Second, there is indeed one step between preprocessing and pre-train: binarize the data before training. I will modify the README.md to make the steps easier to follow. You can refer to the file experiments/example/bin.sh or only run the script below to get the binarized data.
> > > ```shell
> > > # preprocess pre-train train data
> > > fairseq-preprocess \
> > >         --source-lang src --target-lang trg \
> > >         --srcdict ${PROJECT_ROOT}/experiments/toy/vocab/vocab.bpe.${subword_bpe_merge_ops} \
> > >         --tgtdict ${PROJECT_ROOT}/experiments/toy/vocab/vocab.bpe.${subword_bpe_merge_ops} \
> > >         --trainpref ${PROJECT_ROOT}/experiments/toy/merged_data/train \
> > >         --validpref ${PROJECT_ROOT}/experiments/toy/merged_data/dev \
> > >         --destdir ${PROJECT_ROOT}/experiments/toy/data/pre-train \
> > >         --workers ${num_cpus}
> > > ```
> > 
> > 
> > That's cool! Thanks for your reply. And still another question, how many gpus is needed for the results in the paper. Is 4 enough?
> 
> Yes, you can use 4 gpus, and at the same time you can increase `update_freq` to mimic a larger batch size.

Thanks . That's great! And how large should the update_freq be to  reproduce the results in yours papers? Like wmt14 en-de.

**Comment by PANXiao1994** [comment]
> > > > > The output path in train.yml is /data00/home/panxiao.94/experiments/pmnmt/experiments/toy/data/prep/train.
> > > > > But the data path in transformer_big.yml is /data00/home/panxiao.94/experiments/pmnmt/experiments/toy/data/pre-train.
> > > > > So,.. is there some steps lost about the preprocess phase ?
> > > > 
> > > > 
> > > > Hi,
> > > > First, you should note that the final output path is ${merged_output_path} in experiments/example/configs/preprocess/train.yml
> > > > Second, there is indeed one step between preprocessing and pre-train: binarize the data before training. I will modify the README.md to make the steps easier to follow. You can refer to the file experiments/example/bin.sh or only run the script below to get the binarized data.
> > > > ```shell
> > > > # preprocess pre-train train data
> > > > fairseq-preprocess \
> > > >         --source-lang src --target-lang trg \
> > > >         --srcdict ${PROJECT_ROOT}/experiments/toy/vocab/vocab.bpe.${subword_bpe_merge_ops} \
> > > >         --tgtdict ${PROJECT_ROOT}/experiments/toy/vocab/vocab.bpe.${subword_bpe_merge_ops} \
> > > >         --trainpref ${PROJECT_ROOT}/experiments/toy/merged_data/train \
> > > >         --validpref ${PROJECT_ROOT}/experiments/toy/merged_data/dev \
> > > >         --destdir ${PROJECT_ROOT}/experiments/toy/data/pre-train \
> > > >         --workers ${num_cpus}
> > > > ```
> > > 
> > > 
> > > That's cool! Thanks for your reply. And still another question, how many gpus is needed for the results in the paper. Is 4 enough?
> > 
> > 
> > Yes, you can use 4 gpus, and at the same time you can increase `update_freq` to mimic a larger batch size.
> 
> Thanks . That's great! And how large should the update_freq be to reproduce the results in yours papers? Like wmt14 en-de.

You should calculate by your self: normally, it depends on how large you want your batch size to be, the larger `update_freq`, you set, the larger your batch size will be.
