### ISSUE TITLE
This error occurred while running preprocessing, no vocab  found?  vocab.bpe.600: No such file or directory :No such file or directory

### ISSUE THREAD

**Issue by sammichenVV** [linzehui/mRASP#20]
![image](https://user-images.githubusercontent.com/22388079/123216324-fb202600-d4fb-11eb-9a62-0413f7901fee.png)

**Comment by Aliang-CN** [comment]
> ![image](https://user-images.githubusercontent.com/22388079/123216324-fb202600-d4fb-11eb-9a62-0413f7901fee.png)

how you fix it？

**Comment by SerendipitySTAR** [comment]
怎么解决的？
