### ISSUE TITLE
Does fine-tuned model use the same vocabulary as pre-trained model?

### ISSUE THREAD

**Issue by zhangguanqun** [linzehui/mRASP#5]
The pre-trained model use learned joint vocabulary with 64867 tokens, merged by 32k operations. That is the file vocab.bpe.32000.
Does fine-tuned model (e.g. en2de) released in icloud use the same vocabulary file as pre-trained model?

**Comment by linzehui** [comment]
yes

**Comment by zhangguanqun** [comment]
appreciate

**Comment by zhangguanqun** [comment]
If I want to fine-tune this model to support new languages,  new tokens should be added to existing file?
That is, new file has larger vocabulary size than 64867?
If do so, the embedding params of checkpoint (e.g. pretrain_checkpoint_last_RAS.pt) released in this project should be expanded before fine-tuning.

**Comment by PANXiao1994** [comment]
> If I want to fine-tune this model to support new languages, new tokens should be added to existing file?
> That is, new file has larger vocabulary size than 64867?
> If do so, the embedding params of checkpoint (e.g. pretrain_checkpoint_last_RAS.pt) released in this project should be expanded before fine-tuning.

Yes, you are right, if you want to expand the supported languages, you need to merge the newly added tokens into the existing vocabulary, then randomly initialize the embedding vectors of the new tokens.

**Comment by zhangguanqun** [comment]
appreciate * 2
